In [3]:
import numpy as np

Numpy array

In [4]:
benimListem = [20,30,409]

In [5]:
np.array(benimListem)

array([ 20,  30, 409])

In [6]:
matrixListesi =[[10,20],[30,20]]

In [7]:
matrixListesi[1][0]

30

In [8]:
np.array(matrixListesi)

array([[10, 20],
       [30, 20]])

arange

In [9]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Zeros

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

linspance

In [22]:
np.linspace(0, 10, 5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

eye

In [24]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

##random

In [25]:
np.random.randn(8)

array([ 0.70282302, -0.13405895, -0.28694833,  1.77510978, -0.58936299,
        0.61365806, -0.82547788, -0.21310044])

In [26]:
np.random.randn(2,2)

array([[-0.03198711,  0.25358929],
       [-0.38555039,  0.29823567]])

In [38]:
np.random.randint(1,10,3)

array([1, 9, 7])

In [39]:
benimNpDizim= np.arange(10)

In [41]:
benimNpDizim


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
beninDizim = np.random.randint(5,10,10)

In [51]:
beninDizim

array([6, 5, 6, 9, 5, 8, 7, 6, 5, 7])

numpy dizi methodları

In [52]:
beninDizim.reshape(2,5)

array([[6, 5, 6, 9, 5],
       [8, 7, 6, 5, 7]])

In [53]:
benimNpDizim.max()

9

In [56]:
beninDizim.min()

5

In [57]:
beninDizim.argmin()

1

In [58]:
beninDizim.argmax()

3

In [60]:
benimNpDizim.shape

(10,)