In [1]:
import numpy as np

In [2]:
benimDiizm =np.arange(1,6)

In [3]:
benimDiizm

array([1, 2, 3, 4, 5])

In [4]:
benimDiizm[1:3] = -5

In [5]:
benimDiizm

array([ 1, -5, -5,  4,  5])

In [6]:
dizi = np.arange(0,23)

In [7]:
dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [8]:
baskaDizi = dizi[3:10]

In [9]:
baskaDizi


array([3, 4, 5, 6, 7, 8, 9])

In [10]:
baskaDizi[:] =100

In [12]:
baskaDizi

array([100, 100, 100, 100, 100, 100, 100])

In [13]:
dizi

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22])

matrix

In [15]:
benimListem = [[10,20,30],[40,50,60],[70,80,90]]

In [16]:
benimMatrixDizim = np.array(benimListem)

In [17]:
benimMatrixDizim

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [18]:
benimMatrixDizim[0]

array([10, 20, 30])

In [19]:
benimMatrixDizim[0:,2]

array([30, 60, 90])

In [20]:
yeniListe = [[1,2,3,4],[5,6,7,8],[9,10,22,23]]

In [21]:
yeniMatrix = np.array(yeniListe)

In [26]:
yeniMatrix[[0,1,2]]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 22, 23]])

operasyonlar

In [32]:
yeniBirDizi =np.random.randint(5,29,10)

In [33]:
yeniBirDizi

array([23, 14, 14, 21, 14,  8,  8, 23, 27, 13])

In [34]:
yeniBirDizi > 20

array([ True, False, False,  True, False, False, False,  True,  True,
       False])

In [38]:
yeniBirDizi [ yeniBirDizi<10 ]

array([8, 8])

In [39]:
sonDizi = np.arange(0 ,20)

In [40]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [43]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [44]:
np.max(sonDizi)

19

In [45]:
np.min(sonDizi)

0